"""CadQuery script emitter.

The script is the path to the second backend. This package does not import
CadQuery and does not execute the script.
"""

from __future__ import annotations

from typing import Never

from techhand_print_fab.spec import Hole, ModelSpec, hole_depth_mm


def render_cadquery(spec: ModelSpec) -> str:
    if spec.kind == "custom_scad":
        return "\n".join(
            [
                '"""Generated by techhand-print-fab. custom_scad is OpenSCAD-only in v1."""',
                "",
                "result = None",
                "",
            ]
        )
    body = _body(spec)
    return "\n".join(
        [
            '"""Generated by techhand-print-fab. Secondary backend: CadQuery. Units: millimeters."""',
            "",
            "import cadquery as cq",
            "",
            body,
            "",
            "if __name__ == '__main__':",
            "    cq.exporters.export(result, 'model.stl')",
            "    cq.exporters.export(result, 'model.step')",
            "",
        ]
    )


def _body(spec: ModelSpec) -> str:
    match spec.kind:
        case "box":
            solid = _box(spec.length_mm, spec.width_mm, spec.height_mm)
        case "plate" | "mount_plate":
            solid = _box(spec.length_mm, spec.width_mm, spec.thickness_mm)
        case "cylinder":
            solid = (
                f"solid = cq.Workplane('XY').circle({_n(spec.outer_diameter_mm / 2)})."
                f"extrude({_n(spec.height_mm)})"
            )
        case "tube":
            solid = "\n".join(
                [
                    f"outer = cq.Workplane('XY').circle({_n(spec.outer_diameter_mm / 2)}).extrude({_n(spec.height_mm)})",
                    f"inner = cq.Workplane('XY').circle({_n(spec.inner_diameter_mm / 2)}).extrude({_n(spec.height_mm + 0.2)}).translate((0, 0, -0.1))",
                    "solid = outer.cut(inner)",
                ]
            )
        case "l_bracket":
            rise = spec.height_mm - spec.thickness_mm
            solid = "\n".join(
                [
                    _box(spec.length_mm, spec.width_mm, spec.thickness_mm, name="base"),
                    (
                        f"upright = cq.Workplane('XY').box({_n(spec.length_mm)}, {_n(spec.thickness_mm)}, {_n(rise)}, "
                        "centered=(False, False, False))"
                        f".translate((0, {_n(spec.width_mm - spec.thickness_mm)}, {_n(spec.thickness_mm)}))"
                    ),
                    "solid = base.union(upright)",
                ]
            )
        case "custom_scad":
            raise RuntimeError("custom_scad is emitted before the CadQuery body")
        case _ as unhandled:
            _never(unhandled)
    cuts = [_cut(spec, hole) for hole in spec.holes]
    lines = [solid, *cuts, "result = solid"]
    return "\n".join(lines)


def _box(length: float, width: float, height: float, name: str = "solid") -> str:
    return (
        f"{name} = cq.Workplane('XY').box({_n(length)}, {_n(width)}, {_n(height)}, "
        "centered=(False, False, False))"
    )


def _cut(spec: ModelSpec, hole: Hole) -> str:
    depth = _n(hole_depth_mm(spec, hole) + 0.2)
    if hole.face == "upright":
        return (
            "solid = solid.cut("
            f"cq.Workplane('XZ').center({_n(hole.x_mm)}, {_n(hole.y_mm)})"
            f".circle({_n(hole.diameter_mm / 2)}).extrude({depth})"
            f".translate((0, {_n(spec.width_mm + 0.1)}, 0))"
            ")"
        )
    return (
        "solid = solid.cut("
        f"cq.Workplane('XY').center({_n(hole.x_mm)}, {_n(hole.y_mm)})"
        f".circle({_n(hole.diameter_mm / 2)}).extrude({depth}).translate((0, 0, -0.1))"
        ")"
    )


def _n(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text or "0"


def _never(kind: Never) -> Never:
    raise ValueError(f"Unsupported kind: {kind}")
