"""OpenSCAD is the primary geometry backend."""

from __future__ import annotations

from typing import Never

from techhand_print_fab.spec import Hole, ModelSpec, hole_depth_mm


def render_openscad(spec: ModelSpec) -> str:
    lines = [
        "// Generated by techhand-print-fab.",
        "// Primary backend: OpenSCAD. Units: millimeters.",
        "// Re-run fab_param_model after editing params; this file is regenerated.",
        "$fn = 64;",
        _body(spec),
        "",
    ]
    return "\n".join(lines)


def _body(spec: ModelSpec) -> str:
    solid = _solid(spec)
    if not spec.holes:
        return solid
    cuts = "\n".join(_hole(spec, hole) for hole in spec.holes)
    return f"difference() {{\n{solid}\n{cuts}\n}}"


def _solid(spec: ModelSpec) -> str:
    match spec.kind:
        case "box":
            return _prism(spec.length_mm, spec.width_mm, spec.height_mm, spec.corner_radius_mm)
        case "plate" | "mount_plate":
            return _prism(spec.length_mm, spec.width_mm, spec.thickness_mm, spec.corner_radius_mm)
        case "cylinder":
            return f"cylinder(h={_n(spec.height_mm)}, d={_n(spec.outer_diameter_mm)});"
        case "tube":
            return "\n".join(
                [
                    "difference() {",
                    f"  cylinder(h={_n(spec.height_mm)}, d={_n(spec.outer_diameter_mm)});",
                    "  translate([0, 0, -0.1])",
                    f"    cylinder(h={_n(spec.height_mm + 0.2)}, d={_n(spec.inner_diameter_mm)});",
                    "}",
                ]
            )
        case "l_bracket":
            rise = spec.height_mm - spec.thickness_mm
            return "\n".join(
                [
                    "union() {",
                    f"  cube([{_n(spec.length_mm)}, {_n(spec.width_mm)}, {_n(spec.thickness_mm)}]);",
                    f"  translate([0, {_n(spec.width_mm - spec.thickness_mm)}, {_n(spec.thickness_mm)}])",
                    f"    cube([{_n(spec.length_mm)}, {_n(spec.thickness_mm)}, {_n(rise)}]);",
                    "}",
                ]
            )
        case "custom_scad":
            return spec.scad_body.strip()
        case _ as unhandled:
            _never(unhandled)


def _prism(length: float, width: float, height: float, radius: float) -> str:
    if radius <= 0:
        return f"cube([{_n(length)}, {_n(width)}, {_n(height)}]);"
    return "\n".join(
        [
            "hull() {",
            f"  translate([{_n(radius)}, {_n(radius)}, 0]) cylinder(h={_n(height)}, r={_n(radius)});",
            f"  translate([{_n(length - radius)}, {_n(radius)}, 0]) cylinder(h={_n(height)}, r={_n(radius)});",
            f"  translate([{_n(radius)}, {_n(width - radius)}, 0]) cylinder(h={_n(height)}, r={_n(radius)});",
            f"  translate([{_n(length - radius)}, {_n(width - radius)}, 0]) cylinder(h={_n(height)}, r={_n(radius)});",
            "}",
        ]
    )


def _hole(spec: ModelSpec, hole: Hole) -> str:
    diameter = _n(hole.diameter_mm)
    depth = _n(hole_depth_mm(spec, hole) + 0.2)
    if hole.face == "upright":
        return "\n".join(
            [
                f"  translate([{_n(hole.x_mm)}, {_n(spec.width_mm + 0.1)}, {_n(hole.y_mm)}])",
                "    rotate([90, 0, 0])",
                f"      cylinder(h={depth}, d={diameter});",
            ]
        )
    return "\n".join(
        [
            f"  translate([{_n(hole.x_mm)}, {_n(hole.y_mm)}, -0.1])",
            f"    cylinder(h={depth}, d={diameter});",
        ]
    )


def _n(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text or "0"


def _never(kind: Never) -> Never:
    raise ValueError(f"Unsupported kind: {kind}")
